version: "3"

services:
  db:
    volumes:
      - db_data:/data/db
    restart: always
    image: mongo
    ports:
      - "27017:27017"
  app:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /tmp/GeTech/:/usr/share/nginx/html

volumes:
  db_data:
    driver: local
